version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: nordikaventure-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "admin123*"
      MYSQL_DATABASE: "nordikaventure"
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: "./NordikAventure/Dockerfile"
    container_name: nordikaventure-web
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=nordikaventure;User=root;Password=admin123*;"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data: